

table! {
    all_the_types(id) {
        id -> Integer,
        bool_column -> Boolean,
        integer_column -> Integer,
        small_int_col -> SmallInt,
        big_int_col -> BigInt,
        binary_col -> Binary,
        text_col -> Text,
        double_col -> Double,
        float_col -> Float,
        numeric_col -> Numeric,
        date_col -> Date,
        timestamp_col -> Timestamp,
        time_col -> Time,
        float4_col -> Float4,
        small_int2_col -> Smallint,
        int2_col -> Int2,
        int4_col -> Int4,
        int8_col -> Int8,
        big_int2_col -> Bigint,
        float8_col -> Float8,
        decimal_col -> Decimal,
        varchar_col -> VarChar,
        varchar2_col -> Varchar,
        char_col -> Char,
        tinytext_col -> Tinytext,
        mediumtext_col -> Mediumtext,
        tinyblob_col -> Tinyblob,
        blob_col -> Blob,
        longblob_col -> Longblob,
        mediumblob_col -> Mediumblob,
        varbinary_col -> Varbinary,
    }
}
