// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `asd` table.
    ///
    /// (Automatically generated by Diesel.)
    asd (id, qsd) {
        /// The `id` column of the `asd` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `qsd` column of the `asd` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        qsd -> Int4,
    }
}
