#!/bin/sh
set -e

export DATABASE_URL="postgres://localhost/diesel_examples"

for dir in $(find . -type d -maxdepth 1 -mindepth 1); do
  cd $dir
  ../../../bin/diesel database reset
  cargo build
  cd ..
done
