// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `users1` table.
    ///
    /// (Automatically generated by Diesel.)
    users1 (id) {
        /// The `id` column of the `users1` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Nullable<Integer>,
    }
}
