CREATE TABLE numbers (n INTEGER PRIMARY KEY);
CREATE TABLE precision_numbers (n DOUBLE PRECISION NOT NULL PRIMARY KEY);
CREATE TABLE nullable_doubles (id SERIAL PRIMARY KEY, n DOUBLE PRECISION);
CREATE TABLE users_with_name_pk (name VARCHAR PRIMARY KEY);
CREATE TABLE points (x INTEGER NOT NULL, y INTEGER NOT NULL, PRIMARY KEY (x, y));
