#!/bin/sh
set -e

export DATABASE_URL="mysql://localhost/diesel_example"

for dir in $(find . -maxdepth 1 -mindepth 1 -type d); do
  cd $dir
  ../../../bin/diesel database reset
  cargo build
  cd ..
done
