CREATE TABLE unsigned_widths (
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    tiny_value TINYINT UNSIGNED NOT NULL,
    small_value SMALLINT UNSIGNED NOT NULL,
    int_value INTEGER UNSIGNED NOT NULL,
    big_value BIGINT UNSIGNED NOT NULL
) CHARACTER SET utf8mb4;
