CREATE TABLE a (id SERIAL PRIMARY KEY, a INTEGER NOT NULL, b INTEGER NOT NULL);
CREATE UNIQUE INDEX ON a (a, b);
CREATE TABLE b (id SERIAL PRIMARY KEY, a INTEGER, b INTEGER, FOREIGN KEY (a, b) REFERENCES a (a, b));
