use super::{UpdateTarget, IncompleteUpdateStatement};
use super::delete_statement::DeleteStatement;

/// Creates an update statement. Helpers for updating a single row can be
/// generated by
/// [`#[changeset_for]`](https://github.com/sgrif/diesel/tree/master/diesel_codegen#changeset_fortable_name).
///
/// # Example
///
/// # Examples
///
/// ### Deleting a single record:
///
/// ```rust
/// # #[macro_use] extern crate diesel;
/// # include!("src/doctest_setup.rs");
/// #
/// # table! {
/// #     users {
/// #         id -> Serial,
/// #         name -> VarChar,
/// #     }
/// # }
/// #
/// # fn main() {
/// #     use self::users::dsl::*;
/// #     use diesel::query_builder::update;
/// #     let connection = establish_connection();
/// let command = update(users.filter(id.eq(1)))
///     .set(name.eq("James"));
/// let updated_row = connection.query_one(command).unwrap().unwrap();
/// // When passed to `query_one`, the update statement will gain `RETURNING *`
/// assert_eq!((1, "James".to_string()), updated_row);
/// # }
/// ```
pub fn update<T: UpdateTarget>(source: T) -> IncompleteUpdateStatement<T> {
    IncompleteUpdateStatement::new(source)
}

/// Creates a delete statement. Will delete the records in the given set.
/// Because this function has a very generic name, it is not exported by
/// default.
///
/// # Examples
///
/// ### Deleting a single record:
///
/// ```rust
/// # #[macro_use] extern crate diesel;
/// # include!("src/doctest_setup.rs");
/// #
/// # table! {
/// #     users {
/// #         id -> Serial,
/// #         name -> VarChar,
/// #     }
/// # }
/// #
/// # fn main() {
/// #     use self::users::dsl::*;
/// #     use diesel::query_builder::delete;
/// #     let connection = establish_connection();
/// #     let get_count = || users.count().first::<i64>(&connection).unwrap().unwrap();
/// let old_count = get_count();
/// let command = delete(users.filter(id.eq(1)));
/// connection.execute_returning_count(&command).unwrap();
/// assert_eq!(old_count - 1, get_count());
/// # }
/// ```
///
/// ### Deleting a whole table:
///
/// ```rust
/// # #[macro_use] extern crate diesel;
/// # include!("src/doctest_setup.rs");
/// #
/// # table! {
/// #     users {
/// #         id -> Serial,
/// #         name -> VarChar,
/// #     }
/// # }
/// #
/// # fn main() {
/// #     use self::users::dsl::*;
/// #     use diesel::query_builder::delete;
/// #     let connection = establish_connection();
/// #     let get_count = || users.count().first::<i64>(&connection).unwrap().unwrap();
/// connection.execute_returning_count(&delete(users)).unwrap();
/// assert_eq!(0, get_count());
/// # }
/// ```
pub fn delete<T: UpdateTarget>(source: T) -> DeleteStatement<T> {
    DeleteStatement::new(source)
}
