// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `asd` table.
    ///
    /// (Automatically generated by Diesel.)
    asd (id, qsd) {
        /// The `id` column of the `asd` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Nullable<Integer>,
        /// The `qsd` column of the `asd` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        qsd -> Nullable<Integer>,
    }
}
