// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `job` column of the `users` table.
        ///
        /// Its SQL type is `UserJob`.
        ///
        /// (Automatically generated by Diesel.)
        job -> UserJob,
    }
}
