CREATE TABLE IF NOT EXISTS users
(
    id              INTEGER UNSIGNED  NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    account_balance INTEGER DEFAULT 0 NOT NULL
    -- account_balance DECIMAL(32, 16) DEFAULT 0 NOT NULL
)
