#!/bin/sh
set -e

SCRIPT=$(readlink -f $0)
SCRIPTPATH=$(dirname "$SCRIPT")

cd "$SCRIPTPATH"

find . -maxdepth 1 -mindepth 1 -type d | while read -r dir; do
    echo "$dir"
    (cd "$dir" && ./test_all)
done
