#!/bin/sh
set -e

cd ../diesel_cli
cargo build
cd ../examples

# Only step 4 can be run on stable
cd getting_started_step_4
export DATABASE_URL=postgres://localhost/diesel_getting_started_step_4
# FIXME: remove this conditional once cargo workspaces are on stable
if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
  ../../diesel_cli/target/debug/diesel setup
else
  ../../target/debug/diesel setup
fi
cargo build --no-default-features --features "with-syntex"
