#!/bin/sh
set -e

cd ../diesel_cli
cargo build
cd ../examples

# Only step 4 can be run on stable
cd getting_started_step_4
export DATABASE_URL=postgres://localhost/diesel_getting_started_step_4
../../target/debug/diesel setup
cargo build --no-default-features --features "with-syntex"
