// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `with_keywords` table.
    ///
    /// (Automatically generated by Diesel.)
    with_keywords (fn_) {
        /// The `fn` column of the `with_keywords` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        #[sql_name = "fn"]
        fn_ -> Integer,
        /// The `let` column of the `with_keywords` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        #[sql_name = "let"]
        let_ -> Integer,
        /// The `extern` column of the `with_keywords` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        #[sql_name = "extern"]
        extern_ -> Integer,
    }
}
