table! {
    /// Representation of the `user-has-role` table.
    ///
    /// (Automatically generated by Diesel.)
    #[sql_name = "user-has-role"]
    user_has_role (id) {
        /// The `user` column of the `user-has-role` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        user -> Int4,
        /// The `role` column of the `user-has-role` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        role -> Int4,
        /// The `id` column of the `user-has-role` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `created at` column of the `user-has-role` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        #[sql_name = "created at"]
        created_at -> Timestamp,
        /// The `expiry date` column of the `user-has-role` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        #[sql_name = "expiry date"]
        expiry_date -> Nullable<Timestamp>,
    }
}

table! {
    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
    }
}

joinable!(user-has-role -> users (user));

allow_tables_to_appear_in_same_query!(
    user-has-role,
    users,
);
