pub mod custom_schema {
    table! {
        /// Representation of the `custom_schema.a` table.
        ///
        /// (Automatically generated by Diesel.)
        custom_schema.a (id) {
            /// The `id` column of the `custom_schema.a` table.
            ///
            /// Its SQL type is `Int4`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int4,
        }
    }

    table! {
        /// Representation of the `custom_schema.b` table.
        ///
        /// (Automatically generated by Diesel.)
        custom_schema.b (id) {
            /// The `id` column of the `custom_schema.b` table.
            ///
            /// Its SQL type is `Int4`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Int4,
            /// The `parent` column of the `custom_schema.b` table.
            ///
            /// Its SQL type is `Int4`.
            ///
            /// (Automatically generated by Diesel.)
            parent -> Int4,
        }
    }

    joinable!(b -> a (parent));

    allow_tables_to_appear_in_same_query!(
        a,
        b,
    );
}
