// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `users2` table.
    ///
    /// (Automatically generated by Diesel.)
    users2 (id) {
        /// The `id` column of the `users2` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
    }
}
