// @generated automatically by Diesel CLI.

diesel::table! {
    /// table comment
    with_comments (id) {
        /// column comment
        id -> Int4,
        /// The `column_without_comment` column of the `with_comments` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        column_without_comment -> Nullable<Int4>,
    }
}
