CREATE TABLE all_the_ranges (
    int4 INT4RANGE PRIMARY KEY,
    int8 INT8RANGE NOT NULL,
    num NUMRANGE NOT NULL,
    ts TSRANGE NOT NULL,
    tstz TSTZRANGE NOT NULL,
    date DATERANGE NOT NULL
)
