

table! {
    all_the_types(id) {
        id -> Integer,
        bool_column -> Boolean,
        integer_column -> Integer,
        small_int_col -> SmallInt,
        big_int_col -> BigInt,
        text_col -> Text,
        float_col -> Float,
        numeric_col -> Numeric,
        date_col -> Date,
        timestamp_col -> Timestamp,
        time_col -> Time,
        float4_col -> Float4,
        small_int2_col -> Smallint,
        int2_col -> Int2,
        int4_col -> Int4,
        int8_col -> Int8,
        big_int2_col -> Bigint,
        float8_col -> Float8,
        decimal_col -> Decimal,
        varchar_col -> VarChar,
        varchar2_col -> Varchar,
        char_col -> Char,
        bit_col -> Bit,
        cidr_col -> Cidr,
        inet_col -> Inet,
        jsonb_col -> Jsonb,
        macaddr_col -> MacAddr,
        money_col -> Money,
        oid_col -> Oid,
        timestamptz_col -> Timestamptz,
        uuid_col -> Uuid,
        json_col -> Json,
        int4range_col -> Int4range,
        int8range_col -> Int8range,
        daterange_col -> Daterange,
        tsrange_col -> Tsrange,
        tstzrange_col -> Tstzrange,
        small_serial_col -> SmallSerial,
        big_serial_col -> BigSerial,
        serial_col -> Serial,
        bytea_col -> Bytea,
        macaddr2_col -> Macaddr,
    }
}
