CREATE TABLE test(
       id SERIAL PRIMARY KEY,
       "bigint" BIGINT,
       "int8" INT8,
       "bigserial" BIGSERIAL,
       "bigserial2" SERIAL8,
       "boolean" BOOLEAN,
       "bytea" BYTEA,
       "character" character(5),
       "char" char(5),
       "varchar" character varying(5),
       "varchar2" varchar(5),
       "cidr" cidr,
       "date" date,
       "double" double precision,
       "double2" float8,
       "inet" inet,
       "integer" integer,
       "integer2" int,
       "integer3" int4,
       "json" json,
       "jsonb" jsonb,
       "macaddr" macaddr,
       "macaddr8" macaddr8,
       "money" money,
       "numeric" numeric,
       "decimal" decimal,
       "float" real,
       "float2" float4,
       "smallint" smallint,
       "smallint2" int2,
       "smallserial" smallserial,
       "smallserial2" serial2,
       "serial2" serial4,
       "text" text,
       "time" time,
       "timetz" time with time zone,
       "timestamp" timestamp,
       "timestamptz" timestamp with time zone,
       "timestamptz2" timestamptz,
       "uuid" uuid,
       "array"  integer[],
       "array2"  integer ARRAY[4]
);
