// @generated automatically by Diesel CLI.

/// The `MyType` SQL type
///
/// (Automatically generated by Diesel.)
#[derive(diesel::SqlType)]
#[postgres(type_name = "my_type")]
pub struct MyType;

diesel::table! {
    use diesel::sql_types::*;
    use super::MyType;

    /// Representation of the `custom_types` table.
    ///
    /// (Automatically generated by Diesel.)
    custom_types (id) {
        /// The `id` column of the `custom_types` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `custom_enum` column of the `custom_types` table.
        ///
        /// Its SQL type is `MyType`.
        ///
        /// (Automatically generated by Diesel.)
        custom_enum -> MyType,
    }
}
