name: ClusterFuzzLite batch fuzzing
on:
  schedule:
    - cron: '0 06 * * *' # 06:00 UTC daily
permissions: read-all
jobs:
  BatchFuzzing:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
          - address
    steps:
      - name: Build Fuzzers (${{ matrix.sanitizer }})
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: rust
          sanitizer: ${{ matrix.sanitizer }}
      - name: Run Fuzzers (${{ matrix.sanitizer }})
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 3600
          mode: 'batch'
          sanitizer: ${{ matrix.sanitizer }}
          storage-repo: ${{ github.server_url }}/${{ github.repository }}.git
          storage-repo-branch: clusterfuzzlite
