name: ClusterFuzzLite corpus pruning
on:
  schedule:
    - cron: '0 05 * * *' # 05:00 UTC, an hour before batch fuzzing
permissions: read-all
jobs:
  Pruning:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Build Fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: rust
      - name: Run Fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 600
          mode: 'prune'
          storage-repo: ${{ github.server_url }}/${{ github.repository }}.git
          storage-repo-branch: clusterfuzzlite
